### ISSUE TITLE
Warning when used

### ISSUE THREAD

**Issue by danez** [artursvonda/composer-updates#1]
Composer issues a warning when using this plugin

> The "artursvonda/composer-updates" plugin requires composer-plugin-api 1.0.0, this _WILL_ break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by artursvonda** [comment]
Thanks, @danez. Haven't used the plugin for a while myself so didn't have chance to update it. Will try to find the time to take a look at it this weekend.

**Comment by artursvonda** [comment]
@danez Updated dependencies. Also fixed some bugs and created more informative output.

**Comment by danez** [comment]
Thanks, i will try it
